[package]
name = "postscript_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
cron = "0.15.0"
resend-rs = "0.19.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
